- name: "localhost"
  hosts: localhost 
  become_method: sudo
  become_user: root
  become: no
  vars:
    ansible_python_interpreter: python3
    ansible_pkg_mgr: apt
    eclipse_base_dir: "${HOME}/IDE/eclipse" 
  tasks:  
    - name: Include task list
      include: "roles/tasks/main.yml"

    - name: change shell to zsh
      shell: "chsh -s /usr/bin/zsh"
      become: true
