- name: Install brew
  shell: curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh | zsh -
  args:
    executable: /bin/zsh
    warn: no
  become: false

- name: Install brew into path
  shell: echo 'export PATH="/home/linuxbrew/.linuxbrew/bin:$PATH"' >> ~/.zshenv | echo 'eval "$(jenv init -)"' >> ~/.zshrc
  ignore_errors: yes
  become: false

- name: Update brew
  shell: brew update
  ignore_errors: yes
  args:
    executable: /bin/zsh
  become: false

- name: Install lazydocker
  shell: brew install jesseduffield/lazydocker/lazydocker </dev/null
  ignore_errors: yes
  args:
    executable: /bin/zsh
  become: false

- name: Upgrade lazydocker
  shell: brew upgrade jesseduffield/lazydocker/lazydocker </dev/null
  ignore_errors: yes
  args:
    executable: /bin/zsh
  become: false

- name: Install lazygit
  shell: brew install jesseduffield/lazygit/lazygit </dev/null
  ignore_errors: yes
  args:
    executable: /bin/zsh
  become: false

- name: Upgrade lazygit
  shell: brew upgrade jesseduffield/lazygit/lazygit </dev/null
  ignore_errors: yes
  args:
    executable: /bin/zsh
  become: false

- name: Install tig
  shell: brew install tig </dev/null
  ignore_errors: yes
  args:
    executable: /bin/zsh
  become: false

- name: Upgrade tig
  shell: brew upgrade tig </dev/null
  ignore_errors: yes
  args:
    executable: /bin/zsh
  become: false

- name: Install lazynpm
  shell: brew install jesseduffield/lazynpm/lazynpm </dev/null
  ignore_errors: yes
  args:
    executable: /bin/zsh
  become: false

- name: Upgrade lazynpm
  shell: brew upgrade jesseduffield/lazynpm/lazynpm </dev/null
  ignore_errors: yes
  args:
    executable: /bin/zsh
  become: false

- name: Install grv
  shell: brew install grv </dev/null
  ignore_errors: yes
  args:
    executable: /bin/zsh
  become: false

- name: Upgrade grv
  shell: brew upgrade grv </dev/null
  ignore_errors: yes
  args:
    executable: /bin/zsh
  become: false

- name: Install ctop
  shell: brew install ctop </dev/null
  ignore_errors: yes
  args:
    executable: /bin/zsh
  become: false

- name: Upgrade ctop
  shell: brew upgrade ctop </dev/null
  ignore_errors: yes
  args:
    executable: /bin/zsh
  become: false

- name: Install dry
  shell: brew install dry </dev/null
  ignore_errors: yes
  args:
    executable: /bin/zsh
  become: false

- name: Upgrade dry
  shell: brew upgrade ctop </dev/null
  ignore_errors: yes
  args:
    executable: /bin/zsh
  become: false

# - name: using homebrew task
#   homebrew:
#     name: jesseduffield/lazygit/lazygit
#     state: latest