 
---
- name: Install packages with apt 
  apt:
    state: present
    update_cache: yes
    pkg:
      - python3
      - snapd
      - build-essential
      - mc
      - terminator
      - curl
      - wget
      - git
      - git-gui
      - zsh
      - unzip
      - fonts-powerline
      - thefuck
      - maven
      - nodejs
      - npm
      - vagrant
      - pylint
      - python3-pip
      - bat 
      - nnn 
      - fzf
      - openjdk-8-jdk
      - openjdk-11-jdk
      - openjdk-13-jdk
      - openjdk-14-jdk
  ignore_errors: yes 
  become: true

- name: Upgrade all packages to the latest version
  apt:
    name: "*"
    state: latest
  become: true

- include: zsh.yml
- include: docker.yml
- include: jenv.yml
- include: snap.yml
- include: kubernetes.yml
- include: fasd.yml
- include: vim.yml
- include: npm.yml
- include: brew.yml
    

    


  
