 
---
- name: Install packages with apt 
  apt:
    state: present
    update_cache: yes
    pkg:
      - python3
      - snapd
      - build-essential
      - mc
      - terminator
      - curl
      - wget
      - git
      - git-gui
      - zsh
      - unzip
      - fonts-powerline
      - thefuck
      - maven
      - nodejs
      - npm
      - vagrant
      - pylint
      - python3-pip
      - bat 
      - nnn 
      - fzf
      - openjdk-8-jdk
      - openjdk-11-jdk
      - openjdk-13-jdk
      - openjdk-14-jdk
  ignore_errors: yes 
  become: true

- name: Upgrade all packages to the latest version
  apt:
    name: "*"
    state: latest
  become: true

- include: zsh.yml
    
- include: docker.yml

- name: Add an apt signing key for Kubernetes
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present
  become: true

- include: snap.yml

- name: Install Kubebox
  shell: curl -Lo kubebox https://github.com/astefanutti/kubebox/releases/download/v0.8.0/kubebox-linux && chmod +x kubebox
  become: false

- name: Reload profile
  shell: . ${HOME}/.zprofile
  become: false

- name: Adds fasd repo
  apt_repository:
    repo: 'ppa:aacebedo/fasd'
    update_cache: yes
  become: true

- name: Install fasd with apt
  apt: name=fasd state=latest
  become: true

- include: brew.yml

- name: Install spacevim
  shell: curl -sLf https://spacevim.org/install.sh | zsh </dev/null
  ignore_errors: yes
  become: false

- include: npm.yml
    
- name: Install jenv
  git: 
    repo: https://github.com/jenv/jenv.git 
    dest: ~/.jenv


- name: Install Jenv into path
  shell: echo 'export PATH="$HOME/.jenv/bin:$PATH"' >> ~/.zshenv | echo 'eval "$(jenv init -)"' >> ~/.zshrc
  ignore_errors: yes
  become: false
    


  
