- name: Install sdkman 
  shell: curl -s "https://get.sdkman.io"| bash 
  ignore_errors: yes
  become: false

- name: sdkman install java
  shell: sdk install java
  args:
    executable: /bin/bash
    warn: no
  ignore_errors: yes
  become: false

