- name: Install spacevim
  get_url:
      url: https://spacevim.org/install.sh
      dest: /tmp/spacevim-installer.sh
      mode: +x
  become: false

- name: Execute the spacevim-installer.sh
  shell: /tmp/spacevim-installer.sh
  args:
    executable: /bin/zsh
  become: false

- name: Remove the spacevim-installer.sh
  file: path=/tmp/spacevim-installer.sh state=absent
  become: false

- name: init.toml symlink
  file: path=~/.SpaceVim.d/init.toml 
        src=~/GIT/ConfigLinuxFiles/init.toml  
        state=link 
        force=yes

- name: myconfig.vim symlink
  file: path=~/.SpaceVim/autoload/myconfig.vim 
        src=~/GIT/ConfigLinuxFiles/Spacevim/autoload/myconfig.vim
        state=link 
        force=yes
