- name: Check if oh-my-zsh previious installed
  stat: 
    path: ~/.oh-my-zsh
  register: previous_zsh_instalation
  become: false

- name: Cloning  oh-my-zsh
  git:
    repo=https://github.com/robbyrussell/oh-my-zsh
    dest=~/.oh-my-zsh
  register: cloning
  when: previous_zsh_instalation
  become: false

- name: zsh-history-substring-search
  git:
    repo: https://github.com/zsh-users/zsh-history-substring-search.git
    dest: ~/.oh-my-zsh/custom}/plugins/zsh-history-substring-search

- name: Installing git configfiles
  git:
    repo: https://github.com/SalesianosZaragoza/ConfigLinuxFiles.git
    dest: ~/GIT/ConfigLinuxFiles

- name: remove the folder
  file: ~/.zshrc state=absent 

- name: zshrc symlink
  file: 
    src: ~/.zshrc 
    dest: ~/GIT/ConfigLinuxFiles/.zshrc  
    state: link 
    force: yes

- name: Installing zsh completions
  git:
    repo: https://github.com/zsh-users/zsh-completions.git
    dest: ~/.oh-my-zsh/custom/plugins/zsh-completions

- name: Installing zsh-history-substring
  git:
    repo: https://github.com/zsh-users/zsh-history-substring-search.git
    dest: ~/.oh-my-zsh/custom/plugins/zsh-history-substring-search


- name: Installing-pure-prompt
  git:
    repo: https://github.com/sindresorhus/pure.git
    dest: ~/.zsh/pure


