- name: Install microk8s
  snap:
    name:
      - microk8s
    classic: yes
  become: true

- name: Install dbeaver
  snap:
    name:
      - dbeaver-ce
    classic: yes
  become: true

- name: Install vs code
  snap:
    name:
      - code
    classic: yes
  become: true

- name: Install eclipse
  snap:
    name:
      - eclipse
    classic: yes
  become: true